CREATE TABLE tb_user(
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login_id VARCHAR(20) NOT NULL,
	login_password VARCHAR(20) NOT NULL,
	`NAME` VARCHAR(20),
	address VARCHAR(100),
	phone VARCHAR(20),
	error_count INT NOT NULL DEFAULT 0,
	create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_board(
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(20) NOT NULL,
	content VARCHAR(20) NOT NULL,
	user_id BIGINT not NULL,
	create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);